package exclusion

import (
	"bufio"
	"os"
	"path/filepath"
	"strings"
)

// DefaultExcludedDirs are directories always excluded from scanning.
var DefaultExcludedDirs = map[string]bool{
	"node_modules": true,
	"vendor":       true,
	".git":         true,
	"__pycache__":  true,
	".venv":        true,
	"venv":         true,
	"dist":         true,
	"build":        true,
	"out":          true,
	".next":        true,
	".nuxt":        true,
}

// DefaultExcludedExtensions are file extensions always excluded.
var DefaultExcludedExtensions = map[string]bool{
	".min.js":    true,
	".min.css":   true,
	".bundle.js": true,
	".map":       true,
}

// generatedMarkers are header comments that indicate generated files.
var generatedMarkers = []string{
	"DO NOT EDIT",
	"auto-generated",
	"AUTO-GENERATED",
	"Code generated",
	"THIS FILE IS GENERATED",
	"generated by",
}

// ShouldExcludeDir returns true if the directory name should be excluded.
func ShouldExcludeDir(name string) bool {
	return DefaultExcludedDirs[name]
}

// ShouldExcludeFile returns true if the file should be excluded based on
// its name, extension, or content.
func ShouldExcludeFile(path string) bool {
	base := filepath.Base(path)

	// Check compound extensions (e.g., .min.js)
	for ext := range DefaultExcludedExtensions {
		if strings.HasSuffix(base, ext) {
			return true
		}
	}

	return false
}

// IsBinaryFile checks if a file appears to be binary by reading the first
// 512 bytes and looking for null bytes.
func IsBinaryFile(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()

	buf := make([]byte, 512)
	n, err := f.Read(buf)
	if err != nil || n == 0 {
		return false
	}

	for i := 0; i < n; i++ {
		if buf[i] == 0 {
			return true
		}
	}
	return false
}

// IsGeneratedFile checks if a file has a generated file header marker
// in its first 5 lines.
func IsGeneratedFile(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for i := 0; i < 5 && scanner.Scan(); i++ {
		line := scanner.Text()
		for _, marker := range generatedMarkers {
			if strings.Contains(line, marker) {
				return true
			}
		}
	}
	return false
}
