package exclusion

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestShouldExcludeDir(t *testing.T) {
	excluded := []string{"node_modules", "vendor", ".git", "__pycache__", ".venv", "venv", "dist", "build", "out", ".next", ".nuxt"}
	for _, d := range excluded {
		assert.True(t, ShouldExcludeDir(d), "expected %q to be excluded", d)
	}

	notExcluded := []string{"src", "lib", "cmd", "internal", "pkg"}
	for _, d := range notExcluded {
		assert.False(t, ShouldExcludeDir(d), "expected %q to not be excluded", d)
	}
}

func TestShouldExcludeFile(t *testing.T) {
	excluded := []string{"app.min.js", "style.min.css", "main.bundle.js", "app.js.map"}
	for _, f := range excluded {
		assert.True(t, ShouldExcludeFile(f), "expected %q to be excluded", f)
	}

	notExcluded := []string{"main.go", "app.js", "style.css", "README.md"}
	for _, f := range notExcluded {
		assert.False(t, ShouldExcludeFile(f), "expected %q to not be excluded", f)
	}
}

func TestIsBinaryFile(t *testing.T) {
	dir := t.TempDir()

	// Text file
	textFile := filepath.Join(dir, "text.go")
	os.WriteFile(textFile, []byte("package main\nfunc main() {}\n"), 0644)
	assert.False(t, IsBinaryFile(textFile))

	// Binary file (contains null bytes)
	binFile := filepath.Join(dir, "binary.dat")
	os.WriteFile(binFile, []byte{0x89, 0x50, 0x4E, 0x47, 0x00, 0x00, 0x01}, 0644)
	assert.True(t, IsBinaryFile(binFile))

	// Non-existent file
	assert.False(t, IsBinaryFile(filepath.Join(dir, "nonexistent")))
}

func TestIsGeneratedFile(t *testing.T) {
	dir := t.TempDir()

	tests := []struct {
		name     string
		content  string
		expected bool
	}{
		{"do_not_edit", "// DO NOT EDIT\npackage gen\n", true},
		{"auto_generated", "# auto-generated file\nimport foo\n", true},
		{"code_generated", "// Code generated by protoc; DO NOT EDIT.\npackage pb\n", true},
		{"normal_file", "package main\n\nfunc main() {}\n", false},
		{"marker_past_5_lines", "line1\nline2\nline3\nline4\nline5\n// DO NOT EDIT\n", false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			f := filepath.Join(dir, tt.name+".go")
			os.WriteFile(f, []byte(tt.content), 0644)
			assert.Equal(t, tt.expected, IsGeneratedFile(f))
		})
	}
}
