package exclusion

import (
	"bufio"
	"os"
	"path/filepath"
	"strings"
)

// DefaultExcludedDirs are directories always excluded from scanning.
var DefaultExcludedDirs = map[string]bool{
	"node_modules":    true,
	"vendor":          true,
	".git":            true,
	"__pycache__":     true,
	".venv":           true,
	"venv":            true,
	"dist":            true,
	"build":           true,
	"out":             true,
	".next":           true,
	".nuxt":           true,
	"coverage":        true, // test coverage reports (Jest, Istanbul, etc.)
	".nyc_output":     true, // Istanbul/nyc intermediate coverage data
	"storybook-static": true, // Storybook build output
	"deps":             true, // vendored dependencies (common in C/C++ projects like Redis)
	".yarn":            true, // Yarn PnP releases / cache (bundled JS binaries)
}

// AuxiliaryDirPatterns are directory names that contain non-production code
// (scripts, demos, tooling). Files in these dirs are still walked for language
// detection and LOC, but are excluded from quality metrics like duplication.
var AuxiliaryDirPatterns = map[string]bool{
	"examples":  true,
	"example":   true,
	"sandbox":   true,
	"bin":       true,
	"scripts":   true,
	"tools":     true,
	"docs":      true,
	"doc":       true,
	"docs_src":  true, // documentation source examples (e.g. FastAPI tutorial variants)
	"samples":   true,
	"demo":      true,
	"demos":     true,
	"devenv":    true, // local dev environment configs (Docker, dummy credentials)
}

// DefaultExcludedExtensions are file extensions always excluded.
var DefaultExcludedExtensions = map[string]bool{
	".min.js":    true,
	".min.css":   true,
	".bundle.js": true,
	".map":       true,
}

// DefaultExcludedFiles are specific filenames always excluded (lockfiles,
// auto-generated manifests, etc.). These are not source code.
var DefaultExcludedFiles = map[string]bool{
	"package-lock.json": true,
	"yarn.lock":         true,
	"pnpm-lock.yaml":   true,
	"composer.lock":     true,
	"Gemfile.lock":      true,
	"Pipfile.lock":      true,
	"poetry.lock":       true,
	"go.sum":            true,
	"Cargo.lock":        true,
}

// generatedMarkers are header comments that indicate generated files.
var generatedMarkers = []string{
	"DO NOT EDIT",
	"auto-generated",
	"AUTO-GENERATED",
	"Code generated",
	"THIS FILE IS GENERATED",
	"generated by",
}

// ShouldExcludeDir returns true if the directory name should be excluded.
func ShouldExcludeDir(name string) bool {
	return DefaultExcludedDirs[name]
}

// IsAuxiliaryPath returns true if the file path is under an auxiliary
// (non-production) directory like examples/, bin/, sandbox/, docs/.
func IsAuxiliaryPath(relPath string) bool {
	parts := strings.Split(filepath.ToSlash(relPath), "/")
	for _, p := range parts {
		if AuxiliaryDirPatterns[p] {
			return true
		}
	}
	return false
}

// ShouldExcludeFile returns true if the file should be excluded based on
// its name, extension, or content.
func ShouldExcludeFile(path string) bool {
	base := filepath.Base(path)

	// Check lockfiles and auto-generated manifests
	if DefaultExcludedFiles[base] {
		return true
	}

	// Check compound extensions (e.g., .min.js)
	for ext := range DefaultExcludedExtensions {
		if strings.HasSuffix(base, ext) {
			return true
		}
	}

	return false
}

// IsBinaryFile checks if a file appears to be binary by reading the first
// 512 bytes and looking for null bytes.
func IsBinaryFile(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()

	buf := make([]byte, 512)
	n, err := f.Read(buf)
	if err != nil || n == 0 {
		return false
	}

	for i := 0; i < n; i++ {
		if buf[i] == 0 {
			return true
		}
	}
	return false
}

// IsGeneratedFile checks if a file has a generated file header marker
// in its first 5 lines.
func IsGeneratedFile(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for i := 0; i < 5 && scanner.Scan(); i++ {
		line := scanner.Text()
		for _, marker := range generatedMarkers {
			if strings.Contains(line, marker) {
				return true
			}
		}
	}
	return false
}
