package walker

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func createTestFile(t *testing.T, dir, name, content string) {
	t.Helper()
	path := filepath.Join(dir, name)
	os.MkdirAll(filepath.Dir(path), 0755)
	err := os.WriteFile(path, []byte(content), 0644)
	require.NoError(t, err)
}

func TestWalk_BasicProject(t *testing.T) {
	dir := t.TempDir()

	createTestFile(t, dir, "main.go", "package main\n\nfunc main() {\n\tprintln(\"hello\")\n}\n")
	createTestFile(t, dir, "main_test.go", "package main\n\nfunc TestMain(t *testing.T) {\n}\n")
	createTestFile(t, dir, "README.md", "# Hello\n\nThis is a readme.\n")

	result, err := Walk(dir)
	require.NoError(t, err)

	assert.Equal(t, 3, result.TotalFiles)
	assert.Equal(t, 1, result.TestFiles)
	assert.Equal(t, 2, result.SourceFiles)
	assert.Greater(t, result.TotalLOC, 0)
	assert.Greater(t, result.LanguageLOC["Go"], 0)
	assert.Greater(t, result.LanguageLOC["Markdown"], 0)
}

func TestWalk_ExcludesNodeModules(t *testing.T) {
	dir := t.TempDir()

	createTestFile(t, dir, "src/app.js", "const x = 1;\n")
	createTestFile(t, dir, "node_modules/lodash/index.js", "module.exports = {};\n")

	result, err := Walk(dir)
	require.NoError(t, err)

	assert.Equal(t, 1, result.TotalFiles)
	assert.Equal(t, "JavaScript", result.Files[0].Language)
}

func TestWalk_ExcludesMinifiedFiles(t *testing.T) {
	dir := t.TempDir()

	createTestFile(t, dir, "app.js", "const x = 1;\n")
	createTestFile(t, dir, "app.min.js", "var x=1;\n")

	result, err := Walk(dir)
	require.NoError(t, err)

	assert.Equal(t, 1, result.TotalFiles)
}

func TestWalk_ExcludesGeneratedFiles(t *testing.T) {
	dir := t.TempDir()

	createTestFile(t, dir, "regular.go", "package main\n\nfunc main() {}\n")
	createTestFile(t, dir, "generated.go", "// Code generated by protoc; DO NOT EDIT.\npackage pb\n\ntype Foo struct{}\n")

	result, err := Walk(dir)
	require.NoError(t, err)

	assert.Equal(t, 1, result.TotalFiles)
	assert.Equal(t, "regular.go", filepath.Base(result.Files[0].Path))
}

func TestWalk_MultiLanguage(t *testing.T) {
	dir := t.TempDir()

	createTestFile(t, dir, "main.go", "package main\n\nfunc main() {}\n")
	createTestFile(t, dir, "app.py", "def main():\n    print('hello')\n")
	createTestFile(t, dir, "index.ts", "const x: number = 1;\n")
	createTestFile(t, dir, "style.css", "body { color: red; }\n")

	result, err := Walk(dir)
	require.NoError(t, err)

	assert.Equal(t, 4, result.TotalFiles)
	assert.Greater(t, result.LanguageLOC["Go"], 0)
	assert.Greater(t, result.LanguageLOC["Python"], 0)
	assert.Greater(t, result.LanguageLOC["TypeScript"], 0)
	assert.Greater(t, result.LanguageLOC["CSS"], 0)
}

func TestWalk_EmptyDir(t *testing.T) {
	dir := t.TempDir()

	result, err := Walk(dir)
	require.NoError(t, err)
	assert.Equal(t, 0, result.TotalFiles)
	assert.Equal(t, 0, result.TotalLOC)
}

func TestWalk_TestFileClassification(t *testing.T) {
	dir := t.TempDir()

	createTestFile(t, dir, "src/app.ts", "export const x = 1;\n")
	createTestFile(t, dir, "src/app.test.ts", "test('x', () => {});\n")
	createTestFile(t, dir, "src/__tests__/helper.ts", "export const h = 1;\n")
	createTestFile(t, dir, "tests/test_app.py", "def test_app(): pass\n")
	createTestFile(t, dir, "spec/app_spec.rb", "describe 'app' do\nend\n")
	createTestFile(t, dir, "tests/AppTest.php", "class AppTest {}\n")

	result, err := Walk(dir)
	require.NoError(t, err)

	testCount := 0
	for _, f := range result.Files {
		if f.IsTest {
			testCount++
		}
	}
	assert.Equal(t, 5, testCount) // app.test.ts, __tests__/helper.ts, test_app.py, app_spec.rb, AppTest.php
}

func TestCountLOC(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "test.txt")

	content := "line1\n\nline3\n\nline5\n"
	os.WriteFile(path, []byte(content), 0644)

	assert.Equal(t, 3, countLOC(path)) // 3 non-blank lines
}

func TestCountLOC_EmptyFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "empty.txt")
	os.WriteFile(path, []byte(""), 0644)

	assert.Equal(t, 0, countLOC(path))
}

func TestCountLOC_BlankLinesOnly(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "blanks.txt")
	os.WriteFile(path, []byte("\n\n\n\n"), 0644)

	assert.Equal(t, 0, countLOC(path))
}

func TestWalk_BlankOnlyFileSkipped(t *testing.T) {
	dir := t.TempDir()
	createTestFile(t, dir, "real.go", "package main\n\nfunc main() {}\n")
	createTestFile(t, dir, "blank.go", "\n\n\n")

	result, err := Walk(dir)
	require.NoError(t, err)

	// blank.go has LOC 0 and should be skipped
	assert.Equal(t, 1, result.TotalFiles)
	assert.Equal(t, "real.go", filepath.Base(result.Files[0].Path))
}
