source 'https://rubygems.org'

gem 'rails', '~> 5.2.8'
gem 'devise', '~> 4.7.1'
gem 'pg', '~> 1.2'
gem 'puma', '~> 4.3'
gem 'stripe', '~> 5.28'
gem 'rack', '~> 2.1.4'
gem 'nokogiri', '~> 1.10.8'
gem 'activesupport', '~> 5.2.8'

group :test do
  gem 'rspec-rails', '~> 5.0'
  gem 'factory_bot_rails'
end
